spring:
  application:
    name: EcoCity
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123
    url: jdbc:postgresql://localhost:5432/eco_city_db
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
token:
  secret: ecgceybFHGJFAVfavxafARC435ivucqvuzuUWCWrcdyxav3124571xv=
server:
  servlet:
    context-path: /api
appeal:
  photo:
    path: /appeals/photos